name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu yüklə
        uses: actions/checkout@v4

      - name: Python quraşdır
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Playwright yüklə
        run: |
          pip install playwright
          playwright install chromium --with-deps

      - name: Qovluğu yarat və monitoru işə sal
        run: |
          mkdir -p output
          python monitor.py || (echo "PYTHON_SCRIPT_ERROR: Skript işləyərkən xəta baş verdi!" && exit 1)

      - name: M3U yadda saxla və göndər
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin main
          git reset --soft origin/main || true
          git add output/channels.m3u
          git commit -m "Auto-update playlist" || echo "Dəyişiklik yoxdur"
          git push origin main --force
